# Generated by Django 2.2.5 on 2020-08-19 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('chestpics', models.ImageField(upload_to='profiles')),
                ('chest_prediction', models.CharField(default='NA', max_length=30)),
                ('chest_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
