# Generated by Django 2.2.5 on 2020-08-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimg',
            old_name='patient_id',
            new_name='pid',
        ),
    ]
