# Generated by Django 2.2.5 on 2021-06-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200819_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimg',
            old_name='chest_prediction',
            new_name='brain_prediction',
        ),
        migrations.RenameField(
            model_name='uploadimg',
            old_name='chest_score',
            new_name='brain_score',
        ),
        migrations.RenameField(
            model_name='uploadimg',
            old_name='chestpics',
            new_name='brainpics',
        ),
    ]
