# Generated by Django 2.2.5 on 2021-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210609_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimg',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
    ]
